


SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;


CREATE EXTENSION IF NOT EXISTS "pg_net" WITH SCHEMA "extensions";






COMMENT ON SCHEMA "public" IS 'standard public schema';



CREATE EXTENSION IF NOT EXISTS "pg_graphql" WITH SCHEMA "graphql";






CREATE EXTENSION IF NOT EXISTS "pg_stat_statements" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "pgcrypto" WITH SCHEMA "extensions";






CREATE EXTENSION IF NOT EXISTS "supabase_vault" WITH SCHEMA "vault";






CREATE EXTENSION IF NOT EXISTS "uuid-ossp" WITH SCHEMA "extensions";





SET default_tablespace = '';

SET default_table_access_method = "heap";


CREATE TABLE IF NOT EXISTS "public"."all_metrics" (
    "timestamp" timestamp with time zone,
    "device_id" "text",
    "temperature" double precision,
    "main_pressure" double precision,
    "billet_length" double precision,
    "container_temp_front" double precision,
    "container_temp_rear" double precision,
    "production_counter" bigint,
    "current_speed" double precision,
    "extrusion_end_position" double precision
);


ALTER TABLE "public"."all_metrics" OWNER TO "postgres";


CREATE TABLE IF NOT EXISTS "public"."tb_work_log" (
    "id" bigint NOT NULL,
    "created_at" timestamp with time zone DEFAULT "now"(),
    "machine_id" character varying(50) NOT NULL,
    "start_time" timestamp with time zone NOT NULL,
    "end_time" timestamp with time zone NOT NULL,
    "die_id" character varying(50) NOT NULL,
    "worker_name" character varying(50),
    "product_name" character varying(100),
    "alloy_type" character varying(20),
    "target_billet_temp" numeric,
    "target_exit_temp" numeric,
    "production_qty" integer,
    "production_weight" numeric,
    "productivity" numeric,
    "corrected_start_time" timestamp with time zone,
    CONSTRAINT "work_period_check" CHECK (("end_time" > "start_time"))
);


ALTER TABLE "public"."tb_work_log" OWNER TO "postgres";


ALTER TABLE "public"."tb_work_log" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME "public"."tb_work_log_id_seq"
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);



CREATE OR REPLACE VIEW "public"."view_ml_learning_data" AS
 SELECT "m"."timestamp",
    "m"."device_id",
    "m"."main_pressure",
    "m"."current_speed",
    "m"."billet_length",
    "m"."temperature" AS "actual_exit_temp",
    "m"."container_temp_front",
    "m"."container_temp_rear",
    "m"."extrusion_end_position",
    "w"."machine_id",
    "w"."die_id",
    "w"."product_name",
    "w"."alloy_type",
    "w"."worker_name",
    "w"."target_billet_temp",
    "w"."target_exit_temp",
    "w"."production_qty",
        CASE
            WHEN ("w"."production_weight" > (100000)::numeric) THEN ("w"."production_weight" / 1000.0)
            ELSE "w"."production_weight"
        END AS "production_weight",
        CASE
            WHEN ("w"."productivity" > (100000)::numeric) THEN ("w"."productivity" / 1000.0)
            ELSE "w"."productivity"
        END AS "productivity",
    COALESCE("w"."corrected_start_time", ("w"."start_time" - '09:00:00'::interval)) AS "start_time",
    ("w"."end_time" - '09:00:00'::interval) AS "end_time"
   FROM ("public"."all_metrics" "m"
     JOIN "public"."tb_work_log" "w" ON ((("m"."timestamp" >= COALESCE("w"."corrected_start_time", ("w"."start_time" - '09:00:00'::interval))) AND ("m"."timestamp" <= ("w"."end_time" - '09:00:00'::interval)) AND (("w"."machine_id")::"text" = '2호기(창녕)'::"text") AND ("m"."device_id" = ANY (ARRAY['extruder_plc'::"text", 'spot_temperature_sensor'::"text"])))));


ALTER VIEW "public"."view_ml_learning_data" OWNER TO "postgres";


ALTER TABLE ONLY "public"."all_metrics"
    ADD CONSTRAINT "all_metrics_timestamp_device_id_key" UNIQUE ("timestamp", "device_id");



ALTER TABLE ONLY "public"."tb_work_log"
    ADD CONSTRAINT "tb_work_log_pkey" PRIMARY KEY ("id");



ALTER TABLE ONLY "public"."all_metrics"
    ADD CONSTRAINT "unique_metrics_constraint" UNIQUE ("timestamp", "device_id");



CREATE INDEX "idx_work_log_die_id" ON "public"."tb_work_log" USING "btree" ("die_id");



CREATE INDEX "idx_work_log_period" ON "public"."tb_work_log" USING "btree" ("machine_id", "start_time", "end_time");





ALTER PUBLICATION "supabase_realtime" OWNER TO "postgres";





GRANT USAGE ON SCHEMA "public" TO "postgres";
GRANT USAGE ON SCHEMA "public" TO "anon";
GRANT USAGE ON SCHEMA "public" TO "authenticated";
GRANT USAGE ON SCHEMA "public" TO "service_role";














































































































































































GRANT ALL ON TABLE "public"."all_metrics" TO "anon";
GRANT ALL ON TABLE "public"."all_metrics" TO "authenticated";
GRANT ALL ON TABLE "public"."all_metrics" TO "service_role";



GRANT ALL ON TABLE "public"."tb_work_log" TO "anon";
GRANT ALL ON TABLE "public"."tb_work_log" TO "authenticated";
GRANT ALL ON TABLE "public"."tb_work_log" TO "service_role";



GRANT ALL ON SEQUENCE "public"."tb_work_log_id_seq" TO "anon";
GRANT ALL ON SEQUENCE "public"."tb_work_log_id_seq" TO "authenticated";
GRANT ALL ON SEQUENCE "public"."tb_work_log_id_seq" TO "service_role";



GRANT ALL ON TABLE "public"."view_ml_learning_data" TO "anon";
GRANT ALL ON TABLE "public"."view_ml_learning_data" TO "authenticated";
GRANT ALL ON TABLE "public"."view_ml_learning_data" TO "service_role";









ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON SEQUENCES TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON FUNCTIONS TO "service_role";






ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "postgres";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "anon";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "authenticated";
ALTER DEFAULT PRIVILEGES FOR ROLE "postgres" IN SCHEMA "public" GRANT ALL ON TABLES TO "service_role";































