create table public.tb_work_log (
  id bigint generated by default as identity not null,
  created_at timestamp with time zone null default now(),
  machine_id character varying(50) not null,
  start_time timestamp with time zone not null,
  end_time timestamp with time zone not null,
  die_id character varying(50) not null,
  worker_name character varying(50) null,
  product_name character varying(100) null,
  alloy_type character varying(20) null,
  target_billet_temp numeric null,
  target_exit_temp numeric null,
  production_qty integer null,
  production_weight numeric null,
  productivity numeric null,
  corrected_start_time timestamp with time zone null,
  constraint tb_work_log_pkey primary key (id),
  constraint work_period_check check ((end_time > start_time))
) TABLESPACE pg_default;

create index IF not exists idx_work_log_period on public.tb_work_log using btree (machine_id, start_time, end_time) TABLESPACE pg_default;

create index IF not exists idx_work_log_die_id on public.tb_work_log using btree (die_id) TABLESPACE pg_default;