-- Migration: Restore tb_work_log and ensure new columns exist
-- Purpose: Recreate tb_work_log if missing and add new columns safely.

CREATE TABLE IF NOT EXISTS "public"."tb_work_log" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone null default now(),
    "machine_id" character varying(50) not null,
    "start_time" timestamp with time zone not null,
    "end_time" timestamp with time zone not null,
    "die_id" character varying(50) not null,
    "worker_name" character varying(50) null,
    "alloy_type" character varying(20) null,
    "target_billet_temp" numeric null,
    "target_exit_temp" numeric null,
    "production_qty" integer null,
    "production_weight" numeric null,
    "productivity" numeric null,
    "lot" text null,
    "temper_type" text null,
    "quenching_temp" double precision null,
    "stretching" double precision null,
    "total_weight" double precision null,
    "ram" double precision null,
    "product_length" integer null,
    "actual_unit_weight" double precision null,
    "defect_bubble" integer null,
    "defect_tearing" integer null,
    "defect_white_black_line" integer null,
    "defect_oxide" integer null,
    "defect_scratch" integer null,
    "defect_bend" integer null,
    "defect_dimension" integer null,
    "defect_line" integer null,
    "defect_etc" integer null,
    "start_cut" integer null,
    "end_cut" integer null,
    "op_note" text null,
    "die_number" integer null,
    "yield_rate" double precision null,
    constraint "tb_work_log_pkey" primary key ("id"),
    constraint "work_period_check" check (("end_time" > "start_time"))
);

ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "lot" text null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "temper_type" text null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "quenching_temp" double precision null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "stretching" double precision null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "total_weight" double precision null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "ram" double precision null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "product_length" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "actual_unit_weight" double precision null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_bubble" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_tearing" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_white_black_line" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_oxide" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_scratch" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_bend" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_dimension" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_line" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "defect_etc" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "start_cut" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "end_cut" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "op_note" text null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "die_number" integer null;
ALTER TABLE "public"."tb_work_log" ADD COLUMN IF NOT EXISTS "yield_rate" double precision null;

CREATE INDEX IF NOT EXISTS "idx_work_log_die_id" ON "public"."tb_work_log" USING "btree" ("die_id");
CREATE INDEX IF NOT EXISTS "idx_work_log_period" ON "public"."tb_work_log" USING "btree" ("machine_id", "start_time", "end_time");

GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."tb_work_log" TO "anon";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."tb_work_log" TO "authenticated";
GRANT SELECT,INSERT,REFERENCES,DELETE,TRIGGER,TRUNCATE,UPDATE ON TABLE "public"."tb_work_log" TO "service_role";
GRANT SELECT ON TABLE "public"."tb_work_log" TO PUBLIC;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = 'tb_work_log_id_seq'
          AND c.relkind = 'S'
    ) THEN
        GRANT ALL ON SEQUENCE "public"."tb_work_log_id_seq" TO "anon";
        GRANT ALL ON SEQUENCE "public"."tb_work_log_id_seq" TO "authenticated";
        GRANT ALL ON SEQUENCE "public"."tb_work_log_id_seq" TO "service_role";
    END IF;
END $$;
