CREATE TABLE IF NOT EXISTS public.tb_cycle_log (
    id bigint generated by default as identity not null,
    machine_id text not null,
    start_time timestamptz not null,
    end_time timestamptz not null,
    production_counter bigint null,
    work_log_id bigint null,
    duration_sec double precision not null,
    max_pressure double precision not null,
    is_valid boolean not null,
    is_test_run boolean not null default false,
    source_mode text not null,
    algorithm_version text not null,
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    constraint tb_cycle_log_pkey primary key (id),
    constraint tb_cycle_log_time_check check (end_time > start_time)
);

ALTER TABLE public.tb_cycle_log
    ADD COLUMN IF NOT EXISTS machine_id text,
    ADD COLUMN IF NOT EXISTS start_time timestamptz,
    ADD COLUMN IF NOT EXISTS end_time timestamptz,
    ADD COLUMN IF NOT EXISTS production_counter bigint,
    ADD COLUMN IF NOT EXISTS work_log_id bigint,
    ADD COLUMN IF NOT EXISTS duration_sec double precision,
    ADD COLUMN IF NOT EXISTS max_pressure double precision,
    ADD COLUMN IF NOT EXISTS is_valid boolean,
    ADD COLUMN IF NOT EXISTS is_test_run boolean default false,
    ADD COLUMN IF NOT EXISTS source_mode text,
    ADD COLUMN IF NOT EXISTS algorithm_version text,
    ADD COLUMN IF NOT EXISTS created_at timestamptz default now(),
    ADD COLUMN IF NOT EXISTS updated_at timestamptz default now();

UPDATE public.tb_cycle_log
SET
    is_test_run = COALESCE(is_test_run, false),
    source_mode = COALESCE(NULLIF(source_mode, ''), 'legacy_backfill'),
    algorithm_version = COALESCE(NULLIF(algorithm_version, ''), 'pressure_threshold_v1'),
    created_at = COALESCE(created_at, now()),
    updated_at = COALESCE(updated_at, now())
WHERE
    is_test_run IS NULL
    OR source_mode IS NULL
    OR source_mode = ''
    OR algorithm_version IS NULL
    OR algorithm_version = ''
    OR created_at IS NULL
    OR updated_at IS NULL;

DELETE FROM public.tb_cycle_log AS duplicate_target
USING (
    SELECT
        id,
        ROW_NUMBER() OVER (
            PARTITION BY machine_id, start_time, end_time, source_mode, algorithm_version
            ORDER BY updated_at DESC, created_at DESC, id DESC
        ) AS duplicate_rank
    FROM public.tb_cycle_log
) AS ranked
WHERE duplicate_target.id = ranked.id
  AND ranked.duplicate_rank > 1;

UPDATE public.tb_cycle_log AS cycle_log
SET work_log_id = NULL
WHERE work_log_id IS NOT NULL
  AND NOT EXISTS (
      SELECT 1
      FROM public.tb_work_log AS work_log
      WHERE work_log.id = cycle_log.work_log_id
  );

DO $$
BEGIN
    ALTER TABLE public.tb_cycle_log
        ALTER COLUMN machine_id SET NOT NULL,
        ALTER COLUMN start_time SET NOT NULL,
        ALTER COLUMN end_time SET NOT NULL,
        ALTER COLUMN duration_sec SET NOT NULL,
        ALTER COLUMN max_pressure SET NOT NULL,
        ALTER COLUMN is_valid SET NOT NULL,
        ALTER COLUMN is_test_run SET NOT NULL,
        ALTER COLUMN source_mode SET NOT NULL,
        ALTER COLUMN algorithm_version SET NOT NULL,
        ALTER COLUMN created_at SET NOT NULL,
        ALTER COLUMN updated_at SET NOT NULL;

    BEGIN
        ALTER TABLE public.tb_cycle_log
            ADD CONSTRAINT tb_cycle_log_work_log_fk
            FOREIGN KEY (work_log_id)
            REFERENCES public.tb_work_log(id)
            ON DELETE SET NULL;
    EXCEPTION WHEN duplicate_object THEN
        NULL;
    END;
END $$;

DROP INDEX IF EXISTS public.idx_tb_cycle_log_identity;

CREATE UNIQUE INDEX IF NOT EXISTS idx_tb_cycle_log_identity
    ON public.tb_cycle_log (
        machine_id,
        start_time,
        end_time,
        source_mode,
        algorithm_version
    );

CREATE INDEX IF NOT EXISTS idx_tb_cycle_log_work_log_time
    ON public.tb_cycle_log (work_log_id, start_time);

CREATE INDEX IF NOT EXISTS idx_tb_cycle_log_end_time_desc
    ON public.tb_cycle_log (end_time DESC);

GRANT SELECT, INSERT, UPDATE, DELETE ON public.tb_cycle_log TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tb_cycle_log TO authenticated;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.tb_cycle_log TO service_role;
GRANT SELECT ON public.tb_cycle_log TO PUBLIC;

DO $$
BEGIN
    IF EXISTS (
        SELECT 1
        FROM pg_class c
        JOIN pg_namespace n ON n.oid = c.relnamespace
        WHERE n.nspname = 'public'
          AND c.relname = 'tb_cycle_log_id_seq'
          AND c.relkind = 'S'
    ) THEN
        GRANT ALL ON SEQUENCE public.tb_cycle_log_id_seq TO anon;
        GRANT ALL ON SEQUENCE public.tb_cycle_log_id_seq TO authenticated;
        GRANT ALL ON SEQUENCE public.tb_cycle_log_id_seq TO service_role;
    END IF;
END $$;
